version: '3'
services:
  todofrontend:
    image: todofrontend
    depends on:
      - todobackend
    environment:
      - FRONT_HOST=todobackend
    ports:
      - 3000:3000
  
  todobackend:
    image: todobackend
    restart: always
    ports: 
      -3001:3001
  
  todotests:
    image: todotests
    depends_on:
      - todofrontend
      - todobackend
    environment:
      - FRONT_HOST=todofrontend
